# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/test.yaml
    secrets: inherit
