name: Publish to npmjs.com

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: git fetch && git pull origin main
      - run: npm ci -w package
      - run: npm run build --if-present -w package
      - run: npm publish --access public -w package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}