name: "@iwsio/react-blog-examples: PUSH to main"

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/rbe-test.yaml
    secrets: inherit
  set-version:
    needs: run-tests
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/rbe-version.yaml
    secrets: inherit
  publish:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    needs: set-version
    uses: ./.github/workflows/rbe-publish.yaml
    secrets: inherit
