name: "@iwsio/react-blog-examples: PR to main"

on:
  pull_request:
    branches: [ main ]

jobs:
  testing:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v2
    with:
      registry-url: 'https://registry.npmjs.org'
      scope: '@iwsio'
      node-version-file: '.nvmrc'
      cache: npm
      install-command: npm ci
      test-command: npm run test -w packages/fetch
