name: "@iwsio/react-blog-examples: PR to main"

on:
  pull_request:
    branches: [ main ]

jobs:
  testing:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v7
    with:
      registry-url: 'https://registry.npmjs.org'
      scope: '@iwsio'
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      install-command: pnpm install
      test-command: pnpm -F react-blog-examples test
