# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "@iwsio/react-blog-examples: PR to main"

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/rbe-test.yaml
    secrets: inherit
